name: Purge jsDelivr Cache

on:
  workflow_run:
    workflows: ['Increment Semver Tag']
    types: ['completed']
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate List of JS Files to Purge
        id: generate_purge_list
        shell: bash
        run: |
          base_url="https://cdn.jsdelivr.net/gh/${{ github.repository }}@latest"
          urls=""
          if [ -d "dist/prod" ]; then
            for file in $(find dist/prod -type f -name "*.js"); do
              urls+="${base_url}/${file},"
            done
          fi
          urls=${urls%,}  # Remove trailing comma
          echo "urls=$urls" >> $GITHUB_OUTPUT

      - name: Purge jsDelivr Cache
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: ${{ steps.generate_purge_list.outputs.urls }}
